spring.application.name=mype-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.osflbsramgwsctfzeiqy}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Upn-Olivos-2026*}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate: 'update' crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/estampadosproject

supabase.url=${SUPABASE_URL:https://osflbsramgwsctfzeiqy.supabase.co}
# Tu clave anon (o service_role). Para el backend, service_role es mejor porque tiene permisos totales.
supabase.key=${SUPABASE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zZmxic3JhbWd3c2N0ZnplaXF5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4OTU5NjQ1OSwiZXhwIjoyMTA1MTcyNDU5fQ.mdrsqg-I948-vh9QBrhJKxj9tX__baMv-MjVEbvjioI}

# Puerto de ejecución
server.port=8080
server.error.include-message=always
server.error.include-exception=true