spring.application.name=mype-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.jtqdafssdgjdekubmumr}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Pensador95*}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate: 'update' crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/tesis-erp

supabase.url=${SUPABASE_URL:https://jtqdafssdgjdekubmumr.supabase.co}
# Tu clave anon (o service_role). Para el backend, service_role es mejor porque tiene permisos totales.
supabase.key=${SUPABASE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0cWRhZnNzZGdqZGVrdWJtdW1yIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3OTU1OTc3NywiZXhwIjoyMDk1MTM1Nzc3fQ.qBUey17MuLMjnd9jZkGTlX6_luMw6nG6ywLU09E5yQU}

# Puerto de ejecución
server.port=8080
server.error.include-message=always
server.error.include-exception=true